
language: python

python:
  - 3.5
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - pip install python-coveralls

script:
  - coverage run tests.py
  - nosetests --with-coverage -v

after_success:
  - coveralls
  - codecov
